version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - mysql
    build: ./docker
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  mysql_data: